language: node_js
node_js:
  - "5.11"
jdk:
  - oraclejdk8  # needed for local Neo4j 2.0+

env:
  - NEO4J_VERSION="3.0.3"

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # HACK need to change the password initially; changing it and then reverting:
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=neo"
  - curl -vX POST http://neo4j:neo4j2@localhost:7474/user/neo4j/password -d"password=neo4j"
