language: node_js
node_js:
  - "5.11"
jdk:
  - oraclejdk8  # needed for local Neo4j 2.0+

env:
  - NEO4J_VERSION="3.0.3"

before_install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - echo "org.neo4j.server.transaction.timeout=1" >> neo4j-community-$NEO_VERSION/conf/neo4j-server.properties
  - neo4j-community-$NEO_VERSION/bin/neo4j start
  - sleep 10
  - curl -u neo4j:neo4j -H accept:application/json -H content-type:application/json http://localhost:7474/user/neo4j/password -d '{"password":"neo"}'
